export const personalDataDefaultValues = {
  fullName: "",
  preferredName: "",
  email: "",
  phone: "",
  birthDate: "",
  gender: "",
  profession: "",
  address: "",
  number: "",
  complement: "",
  district: "",
  city: "",
  state: "",
  zipCode: "",
};

export const clinicalProfileDefaultValues = {
  hasChronicDisease: "",
  chronicDiseaseDescription: "",
  usesMedication: "",
  medicationDescription: "",
  hasAllergies: "",
  allergiesDescription: "",
  hadSurgery: "",
  surgeryDescription: "",
  hasPain: "",
  painDescription: "",
  isPregnant: "",
};

export const generalConsiderationsDefaultValues = {
  underMedicalCare: "",
  medicalCareDescription: "",
  hasCirculatoryProblem: "",
  circulatoryProblemDescription: "",
  hasPressureProblem: "",
  pressureProblemDescription: "",
  hasRespiratoryProblem: "",
  respiratoryProblemDescription: "",
  hasVaricoseVeins: "",
  hasThrombosisHistory: "",
  hasSpineProblem: "",
  spineProblemDescription: "",
  additionalInfo: "",
};

export const mtcAnamneseDefaultValues = {
  sleepQuality: "",
  appetite: "",
  bowelFunction: "",
  hasUrinaryAlterations: "",
  urinaryAlterationsDescription: "",
  hasMenstrualCycle: "",
  hasMenstrualAlterations: "",
  menstrualAlterationsDescription: "",
  predominantEmotion: "",
  hasPainOrDiscomfort: "",
  painOrDiscomfortDescription: "",
  observations: "",
};
