import type { Metadata } from "next";
import { Sora, Azeret_Mono, Croissant_One } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const azeret = Azeret_Mono({
  variable: "--font-azeret",
  subsets: ["latin"],
  weight: ["400"],
});

const croissant = Croissant_One({
  variable: "--font-croissant",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Ritha Portella",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} ${croissant.variable} ${azeret.variable} antialiased font-sans bg-background text-foreground`}
      >
        <main className="overflow-x-hidden">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
